import createIntlMiddleware from "next-intl/middleware";
import { NextResponse, type NextRequest } from "next/server";

import { routing } from "@/i18n/routing";

/**
 * M-1, M-2, M-3 — dynamic CSP with per-request nonce.
 *
 * Generates a fresh nonce on every navigation/request and propagates it
 * through `x-nonce` so `app/[locale]/layout.tsx` can wire it into:
 *   - `__webpack_nonce__` (chunks lazy-loaded by Next 15 App Router)
 *   - `<MotionConfig nonce>` (style blocks generated by framer-motion)
 *   - any `<Script nonce>` we add manually
 *
 * Locale routing is handled by next-intl (ADR-013) using `as-needed`
 * prefix mode: `/` is the default (pt-BR), `/en` switches to English.
 */

const intlMiddleware = createIntlMiddleware(routing);

// Paths that bypass next-intl entirely (metadata routes, static files served
// outside the [locale] segment, and PT-BR-only legal pages). CSP nonce is
// still applied below.
const INTL_SKIP = [
  /^\/sitemap\.xml$/,
  /^\/robots\.txt$/,
  /^\/favicon\.ico$/,
  /^\/privacy$/,
  /^\/terms$/,
];

function shouldSkipIntl(pathname: string): boolean {
  return INTL_SKIP.some((re) => re.test(pathname));
}

export default function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Let next-intl handle locale detection, redirect, and rewrites for actual
  // page routes. Metadata routes bypass it (otherwise `/sitemap.xml` would
  // be treated as a locale-prefixed page and 404).
  const intlResponse = shouldSkipIntl(pathname)
    ? NextResponse.next({ request })
    : intlMiddleware(request);

  const nonce = Buffer.from(crypto.randomUUID()).toString("base64");

  // style-src: nonce covers <style> blocks injected by framer-motion via
  //   <MotionConfig nonce>. Runtime animations also set `style="..."` on
  //   attributes; CSP nonces do not apply to attributes, so we keep
  //   `style-src-attr 'unsafe-inline'` open. Attribute-level CSS injection
  //   is a much weaker vector than script execution, and bleach already
  //   sanitizes LLM output (SEC-006) before it reaches React.
  const cspHeader = [
    "default-src 'self'",
    // 'wasm-unsafe-eval' + worker-src blob: required by @react-pdf/renderer v4
    // (yoga-layout WASM + blob worker) for client-side PDF export. These do NOT
    // allow JS eval() — much narrower than 'unsafe-eval'.
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic' 'wasm-unsafe-eval'`,
    `style-src 'self' 'nonce-${nonce}'`,
    "style-src-attr 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    "connect-src 'self' data: blob:",
    "worker-src 'self' blob:",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
  ].join("; ");

  // Re-apply next-intl's response with our headers layered on.
  const response = intlResponse ?? NextResponse.next({ request });
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-nonce", nonce);
  requestHeaders.set("content-security-policy", cspHeader);
  response.headers.set("x-nonce", nonce);
  response.headers.set("Content-Security-Policy", cspHeader);
  return response;
}

export const config = {
  matcher: [
    {
      source: "/((?!api|_next/static|_next/image|favicon.ico).*)",
      missing: [
        { type: "header", key: "next-router-prefetch" },
        { type: "header", key: "purpose", value: "prefetch" },
      ],
    },
  ],
};
